#!/usr/bin/env bash
set -euo pipefail
# Generates the shared-rules block inside an AGENTS.md — the cross-vendor standard read
# natively by Codex, Cursor, Copilot, Aider, Gemini CLI, Windsurf and Zed. (Claude Code
# does NOT read AGENTS.md; it gets the same rules via @imports in .claude/CLAUDE.md.)
#
# AGENTS.md has no import mechanism — agents read it literally — so the rule text must be
# inlined rather than referenced.
#
# The block is delimited by markers and spliced in place: anything outside the markers is
# YOUR content and is never touched. A repo with a hand-written AGENTS.md keeps it and
# gains the block at the end. Re-running replaces only the block, so this is idempotent.
#
# Usage: bash scripts/sync-agents-md.sh [target-AGENTS.md]   (defaults to ./AGENTS.md)

REPO="$(cd "$(dirname "$0")/.." && pwd)"
TARGET="${1:-$(pwd)/AGENTS.md}"

BEGIN_MARKER="<!-- BEGIN oees-agents (generated by scripts/sync-agents-md.sh — do not edit inside) -->"
END_MARKER="<!-- END oees-agents -->"

strip_frontmatter() {
  awk 'NR==1 && /^---/ { in_fm=1; next } in_fm && /^---/ { in_fm=0; next } in_fm { next } { print }' "$1"
}

# Build the block body from the canonical rules.
BLOCK="$(mktemp)"
trap 'rm -f "$BLOCK" "$BLOCK.before" "$BLOCK.after"' EXIT

{
  echo "$BEGIN_MARKER"
  echo ""
  echo "## Engineering rules (shared across OEES repos)"
  echo ""
  echo "Maintained in [oees/agents](https://github.com/oees/agents). Re-run the bootstrap"
  echo "to update. Edit them there, not here — changes inside this block are overwritten."
  echo ""
  for rule in "$REPO/rules"/*.md; do
    [ -f "$rule" ] || continue
    name="$(basename "$rule" .md)"
    echo "### ${name}"
    echo ""
    strip_frontmatter "$rule" | sed -e 's/^# /#### /' -e 's/^## /##### /'
    echo ""
  done
  echo "$END_MARKER"
} > "$BLOCK"

begin_count=0
end_count=0
if [ -f "$TARGET" ]; then
  begin_count="$(grep -cF "$BEGIN_MARKER" "$TARGET" || true)"
  end_count="$(grep -cF "$END_MARKER" "$TARGET" || true)"

  if [ "$begin_count" -ne "$end_count" ] || [ "$begin_count" -gt 1 ]; then
    echo "  ✗ $(basename "$TARGET") has malformed generated-block markers" >&2
    exit 1
  fi
fi

if [ ! -f "$TARGET" ]; then
  {
    echo "# AGENTS.md"
    echo ""
    echo "Instructions for coding agents working in this repository."
    echo "Add project-specific context above or below the generated block."
    echo ""
    cat "$BLOCK"
  } > "$TARGET"
  echo "  ✓ created $(basename "$TARGET")"
elif [ "$begin_count" -eq 1 ]; then
  begin_line="$(grep -nF "$BEGIN_MARKER" "$TARGET" | cut -d: -f1)"
  end_line="$(grep -nF "$END_MARKER" "$TARGET" | cut -d: -f1)"
  if [ "$begin_line" -ge "$end_line" ]; then
    echo "  ✗ $(basename "$TARGET") has generated-block markers in the wrong order" >&2
    exit 1
  fi

  # Replace only what is between the markers; preserve everything either side.
  awk -v b="$BEGIN_MARKER" 'index($0, b) { exit } { print }' "$TARGET" > "$BLOCK.before"
  awk -v e="$END_MARKER" 'found { print } index($0, e) { found = 1 }' "$TARGET" > "$BLOCK.after"
  cat "$BLOCK.before" "$BLOCK" "$BLOCK.after" > "$TARGET"
  echo "  ✓ updated the managed block in $(basename "$TARGET")"
else
  # A hand-written AGENTS.md with no block yet — append, never overwrite.
  { echo ""; cat "$BLOCK"; } >> "$TARGET"
  echo "  ✓ appended the managed block to existing $(basename "$TARGET") (your content kept)"
fi
